template: testify
packages:
  UrlShortener/internal/http-server/handlers/url/save:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: "mocks"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      URLSaver:

  UrlShortener/internal/http-server/handlers/redirect:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: "mocks"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      URLGetter:

  UrlShortener/internal/http-server/handlers/auth/login:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: "mocks"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      LoginService:

  UrlShortener/internal/http-server/handlers/auth/register:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: "mocks"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      RegisterService: