services:
  shortener-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST: shortener-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
      POSTGRES_PORT: 5432
    volumes:
      - urls_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [docker_net]

  shortener-migrate:
    image: migrate/migrate:4
    depends_on:
      shortener-db:
        condition: service_healthy
    networks: [docker_net]
    volumes:
      - ./migrations:/migrations:ro
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@shortener-db:5432/shortener?sslmode=disable",
      "up"
    ]
    restart: "no"

  shortener:
    build: .
    depends_on:
      shortener-db:
        condition: service_healthy
    container_name: url_shortener
    environment:
      APP_SECRET: shortener-secret
      CONFIG_PATH: /config/config.yaml
    volumes:
      - ./config:/config:ro
    ports:
      - "8080:8080"
    networks: [docker_net]

volumes:
  urls_pg:

networks:
  docker_net:
    external: true